# Generated by Django 3.2.4 on 2021-06-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_data_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
