# Generated by Django 3.2.4 on 2021-06-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_data_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='password',
            field=models.CharField(max_length=11),
        ),
    ]
