# Generated by Django 3.2.4 on 2021-06-22 16:23

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_data_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='data',
            managers=[
                ('Entry', django.db.models.manager.Manager()),
            ],
        ),
    ]
