# Generated by Django 3.2.4 on 2021-06-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_alter_data_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
